// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: smartbft_rpc.proto

package smart_bft

import (
	smartbftprotos "github.com/hyperledger-labs/SmartBFT/smartbftprotos"
	yolo "github.com/kujourinka/dedtn-trust-edge/semantic/yolo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoteValue int32

const (
	VoteValue_VOTE_ACCEPT    VoteValue = 0
	VoteValue_VOTE_REJECT    VoteValue = 1
	VoteValue_VOTE_UNCERTAIN VoteValue = 2
)

// Enum value maps for VoteValue.
var (
	VoteValue_name = map[int32]string{
		0: "VOTE_ACCEPT",
		1: "VOTE_REJECT",
		2: "VOTE_UNCERTAIN",
	}
	VoteValue_value = map[string]int32{
		"VOTE_ACCEPT":    0,
		"VOTE_REJECT":    1,
		"VOTE_UNCERTAIN": 2,
	}
)

func (x VoteValue) Enum() *VoteValue {
	p := new(VoteValue)
	*p = x
	return p
}

func (x VoteValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoteValue) Descriptor() protoreflect.EnumDescriptor {
	return file_smartbft_rpc_proto_enumTypes[0].Descriptor()
}

func (VoteValue) Type() protoreflect.EnumType {
	return &file_smartbft_rpc_proto_enumTypes[0]
}

func (x VoteValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoteValue.Descriptor instead.
func (VoteValue) EnumDescriptor() ([]byte, []int) {
	return file_smartbft_rpc_proto_rawDescGZIP(), []int{0}
}

type BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*RequestEnvelope     `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_smartbft_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartbft_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_smartbft_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *BlockRequest) GetRequests() []*RequestEnvelope {
	if x != nil {
		return x.Requests
	}
	return nil
}

type RequestEnvelope struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SubmitterId        string                 `protobuf:"bytes,1,opt,name=submitter_id,json=submitterId,proto3" json:"submitter_id,omitempty"` // idName
	ClientId           string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`          // idName
	RequestId          string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`       // snowflake or uuid
	SubmitterSignature []byte                 `protobuf:"bytes,4,opt,name=submitter_signature,json=submitterSignature,proto3" json:"submitter_signature,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RequestEnvelope_SemanticBox
	//	*RequestEnvelope_SemanticVote
	//	*RequestEnvelope_SemanticDecision
	Payload       isRequestEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEnvelope) Reset() {
	*x = RequestEnvelope{}
	mi := &file_smartbft_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEnvelope) ProtoMessage() {}

func (x *RequestEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_smartbft_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEnvelope.ProtoReflect.Descriptor instead.
func (*RequestEnvelope) Descriptor() ([]byte, []int) {
	return file_smartbft_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RequestEnvelope) GetSubmitterId() string {
	if x != nil {
		return x.SubmitterId
	}
	return ""
}

func (x *RequestEnvelope) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RequestEnvelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestEnvelope) GetSubmitterSignature() []byte {
	if x != nil {
		return x.SubmitterSignature
	}
	return nil
}

func (x *RequestEnvelope) GetPayload() isRequestEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RequestEnvelope) GetSemanticBox() *SemanticBox {
	if x != nil {
		if x, ok := x.Payload.(*RequestEnvelope_SemanticBox); ok {
			return x.SemanticBox
		}
	}
	return nil
}

func (x *RequestEnvelope) GetSemanticVote() *SemanticVote {
	if x != nil {
		if x, ok := x.Payload.(*RequestEnvelope_SemanticVote); ok {
			return x.SemanticVote
		}
	}
	return nil
}

func (x *RequestEnvelope) GetSemanticDecision() *SemanticDecision {
	if x != nil {
		if x, ok := x.Payload.(*RequestEnvelope_SemanticDecision); ok {
			return x.SemanticDecision
		}
	}
	return nil
}

type isRequestEnvelope_Payload interface {
	isRequestEnvelope_Payload()
}

type RequestEnvelope_SemanticBox struct {
	SemanticBox *SemanticBox `protobuf:"bytes,5,opt,name=semantic_box,json=semanticBox,proto3,oneof"`
}

type RequestEnvelope_SemanticVote struct {
	SemanticVote *SemanticVote `protobuf:"bytes,6,opt,name=semantic_vote,json=semanticVote,proto3,oneof"`
}

type RequestEnvelope_SemanticDecision struct {
	SemanticDecision *SemanticDecision `protobuf:"bytes,7,opt,name=semantic_decision,json=semanticDecision,proto3,oneof"`
}

func (*RequestEnvelope_SemanticBox) isRequestEnvelope_Payload() {}

func (*RequestEnvelope_SemanticVote) isRequestEnvelope_Payload() {}

func (*RequestEnvelope_SemanticDecision) isRequestEnvelope_Payload() {}

type SemanticBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         *yolo.DetectReply      `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticBox) Reset() {
	*x = SemanticBox{}
	mi := &file_smartbft_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticBox) ProtoMessage() {}

func (x *SemanticBox) ProtoReflect() protoreflect.Message {
	mi := &file_smartbft_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticBox.ProtoReflect.Descriptor instead.
func (*SemanticBox) Descriptor() ([]byte, []int) {
	return file_smartbft_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *SemanticBox) GetReply() *yolo.DetectReply {
	if x != nil {
		return x.Reply
	}
	return nil
}

type SemanticVote struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SemanticId      string                 `protobuf:"bytes,1,opt,name=semantic_id,json=semanticId,proto3" json:"semantic_id,omitempty"`
	ObservationHash string                 `protobuf:"bytes,2,opt,name=observation_hash,json=observationHash,proto3" json:"observation_hash,omitempty"`
	Round           uint64                 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	VoterId         string                 `protobuf:"bytes,4,opt,name=voter_id,json=voterId,proto3" json:"voter_id,omitempty"`
	Vote            VoteValue              `protobuf:"varint,5,opt,name=vote,proto3,enum=yolo.VoteValue" json:"vote,omitempty"`
	VoterSignature  []byte                 `protobuf:"bytes,6,opt,name=voter_signature,json=voterSignature,proto3" json:"voter_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SemanticVote) Reset() {
	*x = SemanticVote{}
	mi := &file_smartbft_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticVote) ProtoMessage() {}

func (x *SemanticVote) ProtoReflect() protoreflect.Message {
	mi := &file_smartbft_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticVote.ProtoReflect.Descriptor instead.
func (*SemanticVote) Descriptor() ([]byte, []int) {
	return file_smartbft_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *SemanticVote) GetSemanticId() string {
	if x != nil {
		return x.SemanticId
	}
	return ""
}

func (x *SemanticVote) GetObservationHash() string {
	if x != nil {
		return x.ObservationHash
	}
	return ""
}

func (x *SemanticVote) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SemanticVote) GetVoterId() string {
	if x != nil {
		return x.VoterId
	}
	return ""
}

func (x *SemanticVote) GetVote() VoteValue {
	if x != nil {
		return x.Vote
	}
	return VoteValue_VOTE_ACCEPT
}

func (x *SemanticVote) GetVoterSignature() []byte {
	if x != nil {
		return x.VoterSignature
	}
	return nil
}

type SemanticDecision struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SemanticId      string                 `protobuf:"bytes,1,opt,name=semantic_id,json=semanticId,proto3" json:"semantic_id,omitempty"`
	ObservationHash string                 `protobuf:"bytes,2,opt,name=observation_hash,json=observationHash,proto3" json:"observation_hash,omitempty"`
	Round           uint64                 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SemanticDecision) Reset() {
	*x = SemanticDecision{}
	mi := &file_smartbft_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticDecision) ProtoMessage() {}

func (x *SemanticDecision) ProtoReflect() protoreflect.Message {
	mi := &file_smartbft_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticDecision.ProtoReflect.Descriptor instead.
func (*SemanticDecision) Descriptor() ([]byte, []int) {
	return file_smartbft_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *SemanticDecision) GetSemanticId() string {
	if x != nil {
		return x.SemanticId
	}
	return ""
}

func (x *SemanticDecision) GetObservationHash() string {
	if x != nil {
		return x.ObservationHash
	}
	return ""
}

func (x *SemanticDecision) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type Metadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ViewId          uint64                 `protobuf:"varint,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	DecisionsInView uint64                 `protobuf:"varint,2,opt,name=decisions_in_view,json=decisionsInView,proto3" json:"decisions_in_view,omitempty"`
	LatestSequence  uint64                 `protobuf:"varint,3,opt,name=latest_sequence,json=latestSequence,proto3" json:"latest_sequence,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_smartbft_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_smartbft_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_smartbft_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *Metadata) GetViewId() uint64 {
	if x != nil {
		return x.ViewId
	}
	return 0
}

func (x *Metadata) GetDecisionsInView() uint64 {
	if x != nil {
		return x.DecisionsInView
	}
	return 0
}

func (x *Metadata) GetLatestSequence() uint64 {
	if x != nil {
		return x.LatestSequence
	}
	return 0
}

type LedgerBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawData       []byte                 `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerBytes) Reset() {
	*x = LedgerBytes{}
	mi := &file_smartbft_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerBytes) ProtoMessage() {}

func (x *LedgerBytes) ProtoReflect() protoreflect.Message {
	mi := &file_smartbft_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerBytes.ProtoReflect.Descriptor instead.
func (*LedgerBytes) Descriptor() ([]byte, []int) {
	return file_smartbft_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *LedgerBytes) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_smartbft_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_smartbft_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_smartbft_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *Result) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_smartbft_rpc_proto protoreflect.FileDescriptor

const file_smartbft_rpc_proto_rawDesc = "" +
	"\n" +
	"\x12smartbft_rpc.proto\x12\x04yolo\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0emessages.proto\x1a\x1csemantic/yolo/yolo_rpc.proto\"A\n" +
	"\fBlockRequest\x121\n" +
	"\brequests\x18\x01 \x03(\v2\x15.yolo.RequestEnvelopeR\brequests\"\xe6\x02\n" +
	"\x0fRequestEnvelope\x12!\n" +
	"\fsubmitter_id\x18\x01 \x01(\tR\vsubmitterId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12/\n" +
	"\x13submitter_signature\x18\x04 \x01(\fR\x12submitterSignature\x126\n" +
	"\fsemantic_box\x18\x05 \x01(\v2\x11.yolo.SemanticBoxH\x00R\vsemanticBox\x129\n" +
	"\rsemantic_vote\x18\x06 \x01(\v2\x12.yolo.SemanticVoteH\x00R\fsemanticVote\x12E\n" +
	"\x11semantic_decision\x18\a \x01(\v2\x16.yolo.SemanticDecisionH\x00R\x10semanticDecisionB\t\n" +
	"\apayload\"6\n" +
	"\vSemanticBox\x12'\n" +
	"\x05reply\x18\x01 \x01(\v2\x11.yolo.DetectReplyR\x05reply\"\xd9\x01\n" +
	"\fSemanticVote\x12\x1f\n" +
	"\vsemantic_id\x18\x01 \x01(\tR\n" +
	"semanticId\x12)\n" +
	"\x10observation_hash\x18\x02 \x01(\tR\x0fobservationHash\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x04R\x05round\x12\x19\n" +
	"\bvoter_id\x18\x04 \x01(\tR\avoterId\x12#\n" +
	"\x04vote\x18\x05 \x01(\x0e2\x0f.yolo.VoteValueR\x04vote\x12'\n" +
	"\x0fvoter_signature\x18\x06 \x01(\fR\x0evoterSignature\"t\n" +
	"\x10SemanticDecision\x12\x1f\n" +
	"\vsemantic_id\x18\x01 \x01(\tR\n" +
	"semanticId\x12)\n" +
	"\x10observation_hash\x18\x02 \x01(\tR\x0fobservationHash\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x04R\x05round\"x\n" +
	"\bMetadata\x12\x17\n" +
	"\aview_id\x18\x01 \x01(\x04R\x06viewId\x12*\n" +
	"\x11decisions_in_view\x18\x02 \x01(\x04R\x0fdecisionsInView\x12'\n" +
	"\x0flatest_sequence\x18\x03 \x01(\x04R\x0elatestSequence\"(\n" +
	"\vLedgerBytes\x12\x19\n" +
	"\braw_data\x18\x01 \x01(\fR\arawData\"\x18\n" +
	"\x06Result\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*A\n" +
	"\tVoteValue\x12\x0f\n" +
	"\vVOTE_ACCEPT\x10\x00\x12\x0f\n" +
	"\vVOTE_REJECT\x10\x01\x12\x12\n" +
	"\x0eVOTE_UNCERTAIN\x10\x022\x8b\x02\n" +
	"\x0fSmartBftService\x12@\n" +
	"\rHandleMessage\x12\x17.smartbftprotos.Message\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\x0eReqMessageCall\x12\x15.yolo.RequestEnvelope\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\x12PullLatestMetadata\x12\x16.google.protobuf.Empty\x1a\x0e.yolo.Metadata\x127\n" +
	"\n" +
	"PullLedger\x12\x16.google.protobuf.Empty\x1a\x11.yolo.LedgerBytesB<Z:github.com/kujourinka/dedtn-trust-edge/consensus/smart_bftb\x06proto3"

var (
	file_smartbft_rpc_proto_rawDescOnce sync.Once
	file_smartbft_rpc_proto_rawDescData []byte
)

func file_smartbft_rpc_proto_rawDescGZIP() []byte {
	file_smartbft_rpc_proto_rawDescOnce.Do(func() {
		file_smartbft_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smartbft_rpc_proto_rawDesc), len(file_smartbft_rpc_proto_rawDesc)))
	})
	return file_smartbft_rpc_proto_rawDescData
}

var file_smartbft_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_smartbft_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_smartbft_rpc_proto_goTypes = []any{
	(VoteValue)(0),                 // 0: yolo.VoteValue
	(*BlockRequest)(nil),           // 1: yolo.BlockRequest
	(*RequestEnvelope)(nil),        // 2: yolo.RequestEnvelope
	(*SemanticBox)(nil),            // 3: yolo.SemanticBox
	(*SemanticVote)(nil),           // 4: yolo.SemanticVote
	(*SemanticDecision)(nil),       // 5: yolo.SemanticDecision
	(*Metadata)(nil),               // 6: yolo.Metadata
	(*LedgerBytes)(nil),            // 7: yolo.LedgerBytes
	(*Result)(nil),                 // 8: yolo.Result
	(*yolo.DetectReply)(nil),       // 9: yolo.DetectReply
	(*smartbftprotos.Message)(nil), // 10: smartbftprotos.Message
	(*emptypb.Empty)(nil),          // 11: google.protobuf.Empty
}
var file_smartbft_rpc_proto_depIdxs = []int32{
	2,  // 0: yolo.BlockRequest.requests:type_name -> yolo.RequestEnvelope
	3,  // 1: yolo.RequestEnvelope.semantic_box:type_name -> yolo.SemanticBox
	4,  // 2: yolo.RequestEnvelope.semantic_vote:type_name -> yolo.SemanticVote
	5,  // 3: yolo.RequestEnvelope.semantic_decision:type_name -> yolo.SemanticDecision
	9,  // 4: yolo.SemanticBox.reply:type_name -> yolo.DetectReply
	0,  // 5: yolo.SemanticVote.vote:type_name -> yolo.VoteValue
	10, // 6: yolo.SmartBftService.HandleMessage:input_type -> smartbftprotos.Message
	2,  // 7: yolo.SmartBftService.ReqMessageCall:input_type -> yolo.RequestEnvelope
	11, // 8: yolo.SmartBftService.PullLatestMetadata:input_type -> google.protobuf.Empty
	11, // 9: yolo.SmartBftService.PullLedger:input_type -> google.protobuf.Empty
	11, // 10: yolo.SmartBftService.HandleMessage:output_type -> google.protobuf.Empty
	11, // 11: yolo.SmartBftService.ReqMessageCall:output_type -> google.protobuf.Empty
	6,  // 12: yolo.SmartBftService.PullLatestMetadata:output_type -> yolo.Metadata
	7,  // 13: yolo.SmartBftService.PullLedger:output_type -> yolo.LedgerBytes
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_smartbft_rpc_proto_init() }
func file_smartbft_rpc_proto_init() {
	if File_smartbft_rpc_proto != nil {
		return
	}
	file_smartbft_rpc_proto_msgTypes[1].OneofWrappers = []any{
		(*RequestEnvelope_SemanticBox)(nil),
		(*RequestEnvelope_SemanticVote)(nil),
		(*RequestEnvelope_SemanticDecision)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smartbft_rpc_proto_rawDesc), len(file_smartbft_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smartbft_rpc_proto_goTypes,
		DependencyIndexes: file_smartbft_rpc_proto_depIdxs,
		EnumInfos:         file_smartbft_rpc_proto_enumTypes,
		MessageInfos:      file_smartbft_rpc_proto_msgTypes,
	}.Build()
	File_smartbft_rpc_proto = out.File
	file_smartbft_rpc_proto_goTypes = nil
	file_smartbft_rpc_proto_depIdxs = nil
}
