// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: smartbft_rpc.proto

package smart_bft

import (
	context "context"
	smartbftprotos "github.com/hyperledger-labs/SmartBFT/smartbftprotos"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmartBftService_HandleMessage_FullMethodName      = "/yolo.SmartBftService/HandleMessage"
	SmartBftService_ReqMessageCall_FullMethodName     = "/yolo.SmartBftService/ReqMessageCall"
	SmartBftService_PullLatestMetadata_FullMethodName = "/yolo.SmartBftService/PullLatestMetadata"
	SmartBftService_PullLedger_FullMethodName         = "/yolo.SmartBftService/PullLedger"
)

// SmartBftServiceClient is the client API for SmartBftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartBftServiceClient interface {
	// call this when sending consensus message
	HandleMessage(ctx context.Context, in *smartbftprotos.Message, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// call this when receiving a forwarded
	ReqMessageCall(ctx context.Context, in *RequestEnvelope, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PullLatestMetadata(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Metadata, error)
	// pull current ledger{Decision, status}
	PullLedger(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LedgerBytes, error)
}

type smartBftServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartBftServiceClient(cc grpc.ClientConnInterface) SmartBftServiceClient {
	return &smartBftServiceClient{cc}
}

func (c *smartBftServiceClient) HandleMessage(ctx context.Context, in *smartbftprotos.Message, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SmartBftService_HandleMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartBftServiceClient) ReqMessageCall(ctx context.Context, in *RequestEnvelope, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SmartBftService_ReqMessageCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartBftServiceClient) PullLatestMetadata(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Metadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Metadata)
	err := c.cc.Invoke(ctx, SmartBftService_PullLatestMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartBftServiceClient) PullLedger(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LedgerBytes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerBytes)
	err := c.cc.Invoke(ctx, SmartBftService_PullLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartBftServiceServer is the server API for SmartBftService service.
// All implementations must embed UnimplementedSmartBftServiceServer
// for forward compatibility.
type SmartBftServiceServer interface {
	// call this when sending consensus message
	HandleMessage(context.Context, *smartbftprotos.Message) (*emptypb.Empty, error)
	// call this when receiving a forwarded
	ReqMessageCall(context.Context, *RequestEnvelope) (*emptypb.Empty, error)
	PullLatestMetadata(context.Context, *emptypb.Empty) (*Metadata, error)
	// pull current ledger{Decision, status}
	PullLedger(context.Context, *emptypb.Empty) (*LedgerBytes, error)
	mustEmbedUnimplementedSmartBftServiceServer()
}

// UnimplementedSmartBftServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmartBftServiceServer struct{}

func (UnimplementedSmartBftServiceServer) HandleMessage(context.Context, *smartbftprotos.Message) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleMessage not implemented")
}
func (UnimplementedSmartBftServiceServer) ReqMessageCall(context.Context, *RequestEnvelope) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReqMessageCall not implemented")
}
func (UnimplementedSmartBftServiceServer) PullLatestMetadata(context.Context, *emptypb.Empty) (*Metadata, error) {
	return nil, status.Error(codes.Unimplemented, "method PullLatestMetadata not implemented")
}
func (UnimplementedSmartBftServiceServer) PullLedger(context.Context, *emptypb.Empty) (*LedgerBytes, error) {
	return nil, status.Error(codes.Unimplemented, "method PullLedger not implemented")
}
func (UnimplementedSmartBftServiceServer) mustEmbedUnimplementedSmartBftServiceServer() {}
func (UnimplementedSmartBftServiceServer) testEmbeddedByValue()                         {}

// UnsafeSmartBftServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartBftServiceServer will
// result in compilation errors.
type UnsafeSmartBftServiceServer interface {
	mustEmbedUnimplementedSmartBftServiceServer()
}

func RegisterSmartBftServiceServer(s grpc.ServiceRegistrar, srv SmartBftServiceServer) {
	// If the following call panics, it indicates UnimplementedSmartBftServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmartBftService_ServiceDesc, srv)
}

func _SmartBftService_HandleMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(smartbftprotos.Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartBftServiceServer).HandleMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartBftService_HandleMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartBftServiceServer).HandleMessage(ctx, req.(*smartbftprotos.Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartBftService_ReqMessageCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartBftServiceServer).ReqMessageCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartBftService_ReqMessageCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartBftServiceServer).ReqMessageCall(ctx, req.(*RequestEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartBftService_PullLatestMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartBftServiceServer).PullLatestMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartBftService_PullLatestMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartBftServiceServer).PullLatestMetadata(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartBftService_PullLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartBftServiceServer).PullLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartBftService_PullLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartBftServiceServer).PullLedger(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartBftService_ServiceDesc is the grpc.ServiceDesc for SmartBftService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartBftService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yolo.SmartBftService",
	HandlerType: (*SmartBftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleMessage",
			Handler:    _SmartBftService_HandleMessage_Handler,
		},
		{
			MethodName: "ReqMessageCall",
			Handler:    _SmartBftService_ReqMessageCall_Handler,
		},
		{
			MethodName: "PullLatestMetadata",
			Handler:    _SmartBftService_PullLatestMetadata_Handler,
		},
		{
			MethodName: "PullLedger",
			Handler:    _SmartBftService_PullLedger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smartbft_rpc.proto",
}
