// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: smartbft_rpc.proto

package smart_bft

import (
	smartbftprotos "github.com/hyperledger-labs/SmartBFT/smartbftprotos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SemanticMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        uint64                 `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticMsg) Reset() {
	*x = SemanticMsg{}
	mi := &file_smartbft_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticMsg) ProtoMessage() {}

func (x *SemanticMsg) ProtoReflect() protoreflect.Message {
	mi := &file_smartbft_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticMsg.ProtoReflect.Descriptor instead.
func (*SemanticMsg) Descriptor() ([]byte, []int) {
	return file_smartbft_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *SemanticMsg) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *SemanticMsg) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type FwdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        uint64                 `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FwdMessage) Reset() {
	*x = FwdMessage{}
	mi := &file_smartbft_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FwdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FwdMessage) ProtoMessage() {}

func (x *FwdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_smartbft_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FwdMessage.ProtoReflect.Descriptor instead.
func (*FwdMessage) Descriptor() ([]byte, []int) {
	return file_smartbft_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *FwdMessage) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *FwdMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_smartbft_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_smartbft_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_smartbft_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_smartbft_rpc_proto protoreflect.FileDescriptor

const file_smartbft_rpc_proto_rawDesc = "" +
	"\n" +
	"\x12smartbft_rpc.proto\x12\x04yolo\x1a\x0emessages.proto\"?\n" +
	"\vSemanticMsg\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\x04R\x06sender\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\">\n" +
	"\n" +
	"FwdMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\x04R\x06sender\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x18\n" +
	"\x06Result\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2~\n" +
	"\x0fSmartBftService\x126\n" +
	"\rHandleMessage\x12\x17.smartbftprotos.Message\x1a\f.yolo.Result\x123\n" +
	"\x11FwdMessageReceive\x12\x10.yolo.FwdMessage\x1a\f.yolo.ResultB+Z)github.com/KujouRinka/consensus/smart_bftb\x06proto3"

var (
	file_smartbft_rpc_proto_rawDescOnce sync.Once
	file_smartbft_rpc_proto_rawDescData []byte
)

func file_smartbft_rpc_proto_rawDescGZIP() []byte {
	file_smartbft_rpc_proto_rawDescOnce.Do(func() {
		file_smartbft_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smartbft_rpc_proto_rawDesc), len(file_smartbft_rpc_proto_rawDesc)))
	})
	return file_smartbft_rpc_proto_rawDescData
}

var file_smartbft_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_smartbft_rpc_proto_goTypes = []any{
	(*SemanticMsg)(nil),            // 0: yolo.SemanticMsg
	(*FwdMessage)(nil),             // 1: yolo.FwdMessage
	(*Result)(nil),                 // 2: yolo.Result
	(*smartbftprotos.Message)(nil), // 3: smartbftprotos.Message
}
var file_smartbft_rpc_proto_depIdxs = []int32{
	3, // 0: yolo.SmartBftService.HandleMessage:input_type -> smartbftprotos.Message
	1, // 1: yolo.SmartBftService.FwdMessageReceive:input_type -> yolo.FwdMessage
	2, // 2: yolo.SmartBftService.HandleMessage:output_type -> yolo.Result
	2, // 3: yolo.SmartBftService.FwdMessageReceive:output_type -> yolo.Result
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smartbft_rpc_proto_init() }
func file_smartbft_rpc_proto_init() {
	if File_smartbft_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smartbft_rpc_proto_rawDesc), len(file_smartbft_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smartbft_rpc_proto_goTypes,
		DependencyIndexes: file_smartbft_rpc_proto_depIdxs,
		MessageInfos:      file_smartbft_rpc_proto_msgTypes,
	}.Build()
	File_smartbft_rpc_proto = out.File
	file_smartbft_rpc_proto_goTypes = nil
	file_smartbft_rpc_proto_depIdxs = nil
}
