// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: rpc.proto

package yolo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	CameraId      int32                  `protobuf:"varint,2,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRequest) Reset() {
	*x = FrameRequest{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRequest) ProtoMessage() {}

func (x *FrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRequest.ProtoReflect.Descriptor instead.
func (*FrameRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *FrameRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *FrameRequest) GetCameraId() int32 {
	if x != nil {
		return x.CameraId
	}
	return 0
}

type DetectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boxes         []*Box                 `protobuf:"bytes,1,rep,name=boxes,proto3" json:"boxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectReply) Reset() {
	*x = DetectReply{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectReply) ProtoMessage() {}

func (x *DetectReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectReply.ProtoReflect.Descriptor instead.
func (*DetectReply) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *DetectReply) GetBoxes() []*Box {
	if x != nil {
		return x.Boxes
	}
	return nil
}

type Box struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	ClassId       int32                  `protobuf:"varint,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	X1            float32                `protobuf:"fixed32,4,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float32                `protobuf:"fixed32,5,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            float32                `protobuf:"fixed32,6,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            float32                `protobuf:"fixed32,7,opt,name=y2,proto3" json:"y2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Box) Reset() {
	*x = Box{}
	mi := &file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Box) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Box) ProtoMessage() {}

func (x *Box) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Box.ProtoReflect.Descriptor instead.
func (*Box) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *Box) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Box) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *Box) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Box) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Box) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *Box) GetX2() float32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *Box) GetY2() float32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\x04yolo\"J\n" +
	"\fFrameRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1b\n" +
	"\tcamera_id\x18\x02 \x01(\x05R\bcameraId\".\n" +
	"\vDetectReply\x12\x1f\n" +
	"\x05boxes\x18\x01 \x03(\v2\t.yolo.BoxR\x05boxes\"\x9f\x01\n" +
	"\x03Box\x12\x1d\n" +
	"\n" +
	"class_name\x18\x01 \x01(\tR\tclassName\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\x05R\aclassId\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x0e\n" +
	"\x02x1\x18\x04 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x05 \x01(\x02R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x06 \x01(\x02R\x02x2\x12\x0e\n" +
	"\x02y2\x18\a \x01(\x02R\x02y22{\n" +
	"\vYoloService\x126\n" +
	"\fCopyAndPaste\x12\x12.yolo.FrameRequest\x1a\x12.yolo.FrameRequest\x124\n" +
	"\vDetectFrame\x12\x12.yolo.FrameRequest\x1a\x11.yolo.DetectReplyB%Z#github.com/KujouRinka/semantic/yolob\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_proto_goTypes = []any{
	(*FrameRequest)(nil), // 0: yolo.FrameRequest
	(*DetectReply)(nil),  // 1: yolo.DetectReply
	(*Box)(nil),          // 2: yolo.Box
}
var file_rpc_proto_depIdxs = []int32{
	2, // 0: yolo.DetectReply.boxes:type_name -> yolo.Box
	0, // 1: yolo.YoloService.CopyAndPaste:input_type -> yolo.FrameRequest
	0, // 2: yolo.YoloService.DetectFrame:input_type -> yolo.FrameRequest
	0, // 3: yolo.YoloService.CopyAndPaste:output_type -> yolo.FrameRequest
	1, // 4: yolo.YoloService.DetectFrame:output_type -> yolo.DetectReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
