// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: rpc.proto

package yolo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	YoloService_CopyAndPaste_FullMethodName = "/yolo.YoloService/CopyAndPaste"
	YoloService_DetectFrame_FullMethodName  = "/yolo.YoloService/DetectFrame"
)

// YoloServiceClient is the client API for YoloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YoloServiceClient interface {
	CopyAndPaste(ctx context.Context, in *FrameRequest, opts ...grpc.CallOption) (*FrameRequest, error)
	DetectFrame(ctx context.Context, in *FrameRequest, opts ...grpc.CallOption) (*DetectReply, error)
}

type yoloServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewYoloServiceClient(cc grpc.ClientConnInterface) YoloServiceClient {
	return &yoloServiceClient{cc}
}

func (c *yoloServiceClient) CopyAndPaste(ctx context.Context, in *FrameRequest, opts ...grpc.CallOption) (*FrameRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FrameRequest)
	err := c.cc.Invoke(ctx, YoloService_CopyAndPaste_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yoloServiceClient) DetectFrame(ctx context.Context, in *FrameRequest, opts ...grpc.CallOption) (*DetectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectReply)
	err := c.cc.Invoke(ctx, YoloService_DetectFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YoloServiceServer is the server API for YoloService service.
// All implementations must embed UnimplementedYoloServiceServer
// for forward compatibility.
type YoloServiceServer interface {
	CopyAndPaste(context.Context, *FrameRequest) (*FrameRequest, error)
	DetectFrame(context.Context, *FrameRequest) (*DetectReply, error)
	mustEmbedUnimplementedYoloServiceServer()
}

// UnimplementedYoloServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedYoloServiceServer struct{}

func (UnimplementedYoloServiceServer) CopyAndPaste(context.Context, *FrameRequest) (*FrameRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyAndPaste not implemented")
}
func (UnimplementedYoloServiceServer) DetectFrame(context.Context, *FrameRequest) (*DetectReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectFrame not implemented")
}
func (UnimplementedYoloServiceServer) mustEmbedUnimplementedYoloServiceServer() {}
func (UnimplementedYoloServiceServer) testEmbeddedByValue()                     {}

// UnsafeYoloServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YoloServiceServer will
// result in compilation errors.
type UnsafeYoloServiceServer interface {
	mustEmbedUnimplementedYoloServiceServer()
}

func RegisterYoloServiceServer(s grpc.ServiceRegistrar, srv YoloServiceServer) {
	// If the following call panics, it indicates UnimplementedYoloServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&YoloService_ServiceDesc, srv)
}

func _YoloService_CopyAndPaste_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YoloServiceServer).CopyAndPaste(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YoloService_CopyAndPaste_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YoloServiceServer).CopyAndPaste(ctx, req.(*FrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _YoloService_DetectFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YoloServiceServer).DetectFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YoloService_DetectFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YoloServiceServer).DetectFrame(ctx, req.(*FrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// YoloService_ServiceDesc is the grpc.ServiceDesc for YoloService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YoloService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yolo.YoloService",
	HandlerType: (*YoloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CopyAndPaste",
			Handler:    _YoloService_CopyAndPaste_Handler,
		},
		{
			MethodName: "DetectFrame",
			Handler:    _YoloService_DetectFrame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
