# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import yolo_rpc_pb2 as yolo__rpc__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in yolo_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class YoloServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CopyAndPaste = channel.unary_unary(
                '/yolo.YoloService/CopyAndPaste',
                request_serializer=yolo__rpc__pb2.FrameRequest.SerializeToString,
                response_deserializer=yolo__rpc__pb2.FrameRequest.FromString,
                _registered_method=True)
        self.DetectFrame = channel.unary_unary(
                '/yolo.YoloService/DetectFrame',
                request_serializer=yolo__rpc__pb2.FrameRequest.SerializeToString,
                response_deserializer=yolo__rpc__pb2.DetectReply.FromString,
                _registered_method=True)


class YoloServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CopyAndPaste(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YoloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CopyAndPaste': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyAndPaste,
                    request_deserializer=yolo__rpc__pb2.FrameRequest.FromString,
                    response_serializer=yolo__rpc__pb2.FrameRequest.SerializeToString,
            ),
            'DetectFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFrame,
                    request_deserializer=yolo__rpc__pb2.FrameRequest.FromString,
                    response_serializer=yolo__rpc__pb2.DetectReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yolo.YoloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yolo.YoloService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class YoloService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CopyAndPaste(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yolo.YoloService/CopyAndPaste',
            yolo__rpc__pb2.FrameRequest.SerializeToString,
            yolo__rpc__pb2.FrameRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yolo.YoloService/DetectFrame',
            yolo__rpc__pb2.FrameRequest.SerializeToString,
            yolo__rpc__pb2.DetectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
